Improve json filter
sebastienros/fluid pull request #430
Opened 2021-12-15 12:12 UTC by Soar360

I replaced the previous call to IMemberAccessor with GetValueAsync method

2021-12-16 14:59 UTC, sebastienros commented
LGTM. Let me know when you are done. Would have been better with some new unit tests if you actually found an issue, or to show what the new calls to `WriteNullValue` are doing.

2021-12-17 01:47 UTC, Soar360 commented
I write a new unit test to show why we should call to `WriteNullValue ` .
I'm done,you can merge this pr now, thanks.

2021-12-17 08:14 UTC, hishamco requested changes

2021-12-17 08:14 UTC, hishamco commented on Fluid.Tests/MiscFiltersTests.cs
> +
Remove extra line

2021-12-17 08:14 UTC, hishamco commented on Fluid.Tests/MiscFiltersTests.cs
> +        private class DictionaryWithoutIndexableTestObjects : ObjectValueBase
Please move this class at the end

2021-12-17 08:14 UTC, hishamco commented on Fluid/Filters/MiscFilters.cs
> +                                if(stack.Contains(value)) fluidValue = StringValue.Create("circular reference detected.");
```csharp
if(stack.Contains(value))
{
    fluidValue = StringValue.Create("Circular reference has been detected.");
}
```

2021-12-17 08:28 UTC, hishamco commented
Looks good, last thing please check why the build fail

2021-12-17 09:01 UTC, Soar360 commented
> Looks good, last thing please check why the build fail

I have fixed the problem of unit test errors.

2021-12-17 10:05 UTC, hishamco approved these changes
LGTM

2022-01-02 23:55 UTC, merged